baseURL: 'https://FlyingFog.github.io' # set https://username.github.io if you are using GitHub Pages
title: Sicheng Hao
theme: hugo-theme-ladder
license: MIT
licenselink: ''
description: 'Homepage of Sicheng Hao'
homepage: 'https://FlyingFog.github.io' # set https://username.github.io
defaultContentLanguage: 'en'
googleAnalytics: G-KWWFBC1Q0Q
pagination.pagerSize: 10
hasCJKLanguage: true
copyright: "2023 FlyingFog All rights reserved"
Author:
  name: "Sicheng Hao"
  email: "flyingfog@foxmail.com"
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Art
      url: /art
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: Archive
      url: /archives
      weight: 4
    # - name: Guest
    #   url: /guestbook
    #   weight: 5
    # - name: Monitor
    #   url: https://umami-ochre-nu.vercel.app/share/o3zAba1V/guangzhengli
    #   weight: 6
params:
  brand: HOME
  avatarURL: /images/avatar.jpg
  avatarURL2: /images/avatar2.jpg
  author: Sicheng Hao
  authorDescription: A normal student
  info:  A graduate student working on software engineering at the Inplus Lab of Sun Yat-sen University.  # information of your blog site
  favicon: favicon.png                                               # blog site icon，replace your avatar in the /static/images/
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode
  # sponsors:
  #   title: Sponsors
  # comments:
  #   giscus:
  #     enable: true
  #     repo: guangzhengli/hugo-ladder-exampleSite
  #     repo_id: R_kgDOHyVOjg
  #     category: Announcements
  #     category_id: DIC_kwDOHyVOjs4CQsH7
  #     mapping: pathname
  #     position: top
  #     lang: en # pick a language from https://github.com/giscus/giscus/tree/main/locales
  #   utteranc:
  #     enable: false
  #     repo: guangzhengli/blog-comments
  #     issueTerm: pathname
  analytics:
    google:
      SiteVerificationTag: xxx
    # umami:
    #   enable: true
    #   website_id: 2320eaa6-a90b-471c-b6ca-e79dadde8c4c
    #   url: https://umami-ochre-nu.vercel.app/hugo-ladder.js
  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything –- question, appreciation, information, or even humor.
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/FlyingFog'
    - name: Email
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"> <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path> <polyline points="22,6 12,13 2,6"></polyline></svg>
      url: 'mailto:haosch@mail2.sysu.edu.cn'
languages:
  en:
    languageName: EN
  zh:
    languageName: 中
    author: Hao Sicheng
    authorDescription: 一个美观，快速并且专注于阅读的主题
    info: 帮助开发者构建一个免费并且漂亮的博客网站，记录自己的思考并且提高自己的影响力
    # guestbook:
    #   title: 留言板
    #   description: 您的评论，会让该网站更精彩！
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 生活
          url: /art
          weight: 2
        - name: 标签
          url: /tags
          weight: 3
        - name: 历史
          url: /archives
          weight: 3
        # - name: 留言板
        #   url: /guestbook
        #   weight: 4
        # - name: 统计
        #   url: https://umami-ochre-nu.vercel.app/share/o3zAba1V/guangzhengli
        #   weight: 5
taxonomies:
  series: series
  tag: tags
